"""add conflict tracking fields to document metadata

Revision ID: 1ce31578702e
Revises: feac03154a3c
Create Date: 2026-05-10 02:59:52.474758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce31578702e'
down_revision: Union[str, None] = 'feac03154a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_metadata",
        sa.Column(
            "conflict_found",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )

    op.add_column(
        "document_metadata",
        sa.Column(
            "conflict_summary",
            sa.Text(),
            nullable=True,
        ),
    )

    op.add_column(
        "document_metadata",
        sa.Column(
            "conflict_checked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.create_index(
        op.f("ix_document_metadata_conflict_found"),
        "document_metadata",
        ["conflict_found"],
        unique=False,
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_metadata_conflict_found'), table_name='document_metadata')
    op.drop_column('document_metadata', 'conflict_checked_at')
    op.drop_column('document_metadata', 'conflict_summary')
    op.drop_column('document_metadata', 'conflict_found')
    # ### end Alembic commands ###
