"""create document audit logs

Revision ID: 3e21d456075b
Revises: c71dca8e7d03
Create Date: 2026-05-09 20:17:00.492406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e21d456075b'
down_revision: Union[str, None] = 'c71dca8e7d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_audit_logs_action'), 'document_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_document_audit_logs_actor_user_id'), 'document_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_document_audit_logs_document_id'), 'document_audit_logs', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_audit_logs_document_id'), table_name='document_audit_logs')
    op.drop_index(op.f('ix_document_audit_logs_actor_user_id'), table_name='document_audit_logs')
    op.drop_index(op.f('ix_document_audit_logs_action'), table_name='document_audit_logs')
    op.drop_table('document_audit_logs')
    # ### end Alembic commands ###
