"""add cleaned text filename to document metadata

Revision ID: 7c08cba7d697
Revises: 3e21d456075b
Create Date: 2026-05-10 01:38:26.925804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c08cba7d697'
down_revision: Union[str, None] = '3e21d456075b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('cleaned_text_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_metadata', 'cleaned_text_filename')
    # ### end Alembic commands ###
