"""add celery task id to document metadata

Revision ID: c71dca8e7d03
Revises: aeb967f145cc
Create Date: 2026-05-08 22:27:52.829583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71dca8e7d03'
down_revision: Union[str, None] = 'aeb967f145cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_document_metadata_celery_task_id'), 'document_metadata', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_metadata_celery_task_id'), table_name='document_metadata')
    op.drop_column('document_metadata', 'celery_task_id')
    # ### end Alembic commands ###
