"""add qdrant indexing fields to document metadata

Revision ID: feac03154a3c
Revises: 7c08cba7d697
Create Date: 2026-05-10 01:57:56.095342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feac03154a3c'
down_revision: Union[str, None] = '7c08cba7d697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_metadata', sa.Column('qdrant_point_id', sa.UUID(), nullable=True))
    op.add_column('document_metadata', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_document_metadata_qdrant_point_id'), 'document_metadata', ['qdrant_point_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_metadata_qdrant_point_id'), table_name='document_metadata')
    op.drop_column('document_metadata', 'indexed_at')
    op.drop_column('document_metadata', 'qdrant_point_id')
    # ### end Alembic commands ###
